# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeBoilerplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeBoilerplate

  target 'ReactNativeBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeBoilerplate-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeBoilerplate-tvOS

  target 'ReactNativeBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
